package negocio;
// Generated 07/10/2017 19:33:54 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AtestadoId generated by hbm2java
 */
@Embeddable
public class AtestadoId  implements java.io.Serializable {


     private int idAtestado;
     private int medicoId;

    public AtestadoId() {
    }

    public AtestadoId(int idAtestado, int medicoId) {
       this.idAtestado = idAtestado;
       this.medicoId = medicoId;
    }
   


    @Column(name="id_atestado", nullable=false)
    public int getIdAtestado() {
        return this.idAtestado;
    }
    
    public void setIdAtestado(int idAtestado) {
        this.idAtestado = idAtestado;
    }


    @Column(name="medico_id", nullable=false)
    public int getMedicoId() {
        return this.medicoId;
    }
    
    public void setMedicoId(int medicoId) {
        this.medicoId = medicoId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AtestadoId) ) return false;
		 AtestadoId castOther = ( AtestadoId ) other; 
         
		 return (this.getIdAtestado()==castOther.getIdAtestado())
 && (this.getMedicoId()==castOther.getMedicoId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAtestado();
         result = 37 * result + this.getMedicoId();
         return result;
   }   


}


