package negocio;
// Generated 07/10/2017 19:33:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Cargo generated by hbm2java
 */
@Entity
@Table(name="cargo"
    ,catalog="sistemaclinica"
)
public class Cargo  implements java.io.Serializable {


     private Integer idCargo;
     private String nome;
     private Set funcionarios = new HashSet(0);
     private Set riscosOcupacionaises = new HashSet(0);

    public Cargo() {
    }

	
    public Cargo(String nome) {
        this.nome = nome;
    }
    public Cargo(String nome, Set funcionarios, Set riscosOcupacionaises) {
       this.nome = nome;
       this.funcionarios = funcionarios;
       this.riscosOcupacionaises = riscosOcupacionaises;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_cargo", unique=true, nullable=false)
    public Integer getIdCargo() {
        return this.idCargo;
    }
    
    public void setIdCargo(Integer idCargo) {
        this.idCargo = idCargo;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="cargo")
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="cargo_has_riscos_ocupacionais", catalog="sistemaclinica", joinColumns = { 
        @JoinColumn(name="cargo_id_cargo", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="riscos_ocupacionais_id_riscos", nullable=false, updatable=false) })
    public Set getRiscosOcupacionaises() {
        return this.riscosOcupacionaises;
    }
    
    public void setRiscosOcupacionaises(Set riscosOcupacionaises) {
        this.riscosOcupacionaises = riscosOcupacionaises;
    }




}


