package negocio;
// Generated 07/10/2017 19:33:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Empresa generated by hbm2java
 */
@Entity
@Table(name="empresa"
    ,catalog="sistemaclinica"
)
public class Empresa  implements java.io.Serializable {


     private Integer idEmpresa;
     private Empresa empresa;
     private String cnpj;
     private String nomeFantasia;
     private String endereco;
     private String telefone;
     private Set funcionarios = new HashSet(0);
     private Set exames = new HashSet(0);
     private Set empresas = new HashSet(0);

    public Empresa() {
    }

	
    public Empresa(String cnpj, String nomeFantasia, String endereco, String telefone) {
        this.cnpj = cnpj;
        this.nomeFantasia = nomeFantasia;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Empresa(Empresa empresa, String cnpj, String nomeFantasia, String endereco, String telefone, Set funcionarios, Set exames, Set empresas) {
       this.empresa = empresa;
       this.cnpj = cnpj;
       this.nomeFantasia = nomeFantasia;
       this.endereco = endereco;
       this.telefone = telefone;
       this.funcionarios = funcionarios;
       this.exames = exames;
       this.empresas = empresas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_empresa", unique=true, nullable=false)
    public Integer getIdEmpresa() {
        return this.idEmpresa;
    }
    
    public void setIdEmpresa(Integer idEmpresa) {
        this.idEmpresa = idEmpresa;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_id")
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="cnpj", nullable=false, length=20)
    public String getCnpj() {
        return this.cnpj;
    }
    
    public void setCnpj(String cnpj) {
        this.cnpj = cnpj;
    }

    
    @Column(name="nome_fantasia", nullable=false, length=50)
    public String getNomeFantasia() {
        return this.nomeFantasia;
    }
    
    public void setNomeFantasia(String nomeFantasia) {
        this.nomeFantasia = nomeFantasia;
    }

    
    @Column(name="endereco", nullable=false, length=200)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="telefone", nullable=false, length=20)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getFuncionarios() {
        return this.funcionarios;
    }
    
    public void setFuncionarios(Set funcionarios) {
        this.funcionarios = funcionarios;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="empresa_has_exame", catalog="sistemaclinica", joinColumns = { 
        @JoinColumn(name="empresa_id_empresa", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="exame_id_exame", nullable=false, updatable=false) })
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="empresa")
    public Set getEmpresas() {
        return this.empresas;
    }
    
    public void setEmpresas(Set empresas) {
        this.empresas = empresas;
    }




}


