package negocio;
// Generated 07/10/2017 19:33:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionario generated by hbm2java
 */
@Entity
@Table(name="funcionario"
    ,catalog="sistemaclinica"
)
public class Funcionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private Cargo cargo;
     private Empresa empresa;
     private String nome;
     private String cpf;
     private Date dataNascimento;
     private String endereco;
     private String telefone;
     private Set exames = new HashSet(0);

    public Funcionario() {
    }

	
    public Funcionario(String nome, String cpf, Date dataNascimento, String endereco, String telefone) {
        this.nome = nome;
        this.cpf = cpf;
        this.dataNascimento = dataNascimento;
        this.endereco = endereco;
        this.telefone = telefone;
    }
    public Funcionario(Cargo cargo, Empresa empresa, String nome, String cpf, Date dataNascimento, String endereco, String telefone, Set exames) {
       this.cargo = cargo;
       this.empresa = empresa;
       this.nome = nome;
       this.cpf = cpf;
       this.dataNascimento = dataNascimento;
       this.endereco = endereco;
       this.telefone = telefone;
       this.exames = exames;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_funcionario", unique=true, nullable=false)
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cargo_id_cargo")
    public Cargo getCargo() {
        return this.cargo;
    }
    
    public void setCargo(Cargo cargo) {
        this.cargo = cargo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="empresa_id_empresa")
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    
    @Column(name="nome", nullable=false, length=100)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="cpf", nullable=false, length=20)
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_nascimento", nullable=false, length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="endereco", nullable=false, length=200)
    public String getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(String endereco) {
        this.endereco = endereco;
    }

    
    @Column(name="telefone", nullable=false, length=20)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="funcionario_has_exame", catalog="sistemaclinica", joinColumns = { 
        @JoinColumn(name="funcionario_id_funcionario", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="exame_id_exame", nullable=false, updatable=false) })
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }




}


