package negocio;
// Generated 07/10/2017 19:33:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * RiscosOcupacionais generated by hbm2java
 */
@Entity
@Table(name="riscos_ocupacionais"
    ,catalog="sistemaclinica"
)
public class RiscosOcupacionais  implements java.io.Serializable {


     private Integer idRiscos;
     private String nome;
     private Set cargos = new HashSet(0);

    public RiscosOcupacionais() {
    }

	
    public RiscosOcupacionais(String nome) {
        this.nome = nome;
    }
    public RiscosOcupacionais(String nome, Set cargos) {
       this.nome = nome;
       this.cargos = cargos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_riscos", unique=true, nullable=false)
    public Integer getIdRiscos() {
        return this.idRiscos;
    }
    
    public void setIdRiscos(Integer idRiscos) {
        this.idRiscos = idRiscos;
    }

    
    @Column(name="nome", nullable=false, length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="cargo_has_riscos_ocupacionais", catalog="sistemaclinica", joinColumns = { 
        @JoinColumn(name="riscos_ocupacionais_id_riscos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="cargo_id_cargo", nullable=false, updatable=false) })
    public Set getCargos() {
        return this.cargos;
    }
    
    public void setCargos(Set cargos) {
        this.cargos = cargos;
    }




}


