package negocio;
// Generated 07/10/2017 19:33:54 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoExame generated by hbm2java
 */
@Entity
@Table(name="tipo_exame"
    ,catalog="sistemaclinica"
)
public class TipoExame  implements java.io.Serializable {


     private Integer idTipoExame;
     private String tipo;
     private Set exames = new HashSet(0);

    public TipoExame() {
    }

	
    public TipoExame(String tipo) {
        this.tipo = tipo;
    }
    public TipoExame(String tipo, Set exames) {
       this.tipo = tipo;
       this.exames = exames;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id_tipo_exame", unique=true, nullable=false)
    public Integer getIdTipoExame() {
        return this.idTipoExame;
    }
    
    public void setIdTipoExame(Integer idTipoExame) {
        this.idTipoExame = idTipoExame;
    }

    
    @Column(name="tipo", nullable=false, length=50)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="tipoExame")
    public Set getExames() {
        return this.exames;
    }
    
    public void setExames(Set exames) {
        this.exames = exames;
    }




}


